package: api
output: api/server.gen.go
output-options:
  skip-prune: true
  name-normalizer: ToCamelCaseWithInitialisms
generate:
  models: true
  embedded-spec: true
  gorilla-server: true
compatibility:
  always-prefix-enum-values: true

